name: Deploy to Server

on:
  push:
    branches:
      - actions  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.PVM_HOST }} >> ~/.ssh/known_hosts


    - name: Execute deployment commands
      env:
          HOST: ${{ secrets.PVM_HOST }}
          USERNAME: ${{ secrets.PVM_USERNAME }}
      run: |
        if [ -z "$USERNAME" ]; then
          echo "Error: USERNAME is not set."
          exit 1
        fi
        ssh $USERNAME@$HOST << 'ENDSSH'
          cd ~/Projects/Postman.Express
          git pull origin main
          cd consumer_app
          npm i
          npm run build
          npm run prod-api
          cd ../driver_app
          npm i
          npm run build
          npm run prod-api
          cd ../locker_app
          npm i
          npm run build
          npm run prod-api
          cd ../organization_api
          npm i
          npm run prod-api
        ENDSSH
