name: Postman.Express applications runner

on:
  push:
    branches: ["actions"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Deploy to PVM
        env:
          PVM_HOST: ${{ secrets.PVM_HOST }}
          PVM_USERNAME: ${{ secrets.PVM_USERNAME }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh-keyscan -H "$PVM_HOST" >> ~/.ssh/known_hosts
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem $PVM_USERNAME@$PVM_HOST << 'ENDSSH'
            cd ~/Projects/Postman.Express
            git pull origin main
            cd ~/Projects/Postman.Express/consumer_app
            npm i
            npm run build
            npm run prod-api
            cd ~/Projects/Postman.Express/driver_app
            npm i
            npm run build
            npm run prod-api
            cd ~/Projects/Postman.Express/locker_app
            npm i
            npm run build
            npm run prod-api
            cd ~/Projects/Postman.Express/organization_api
            npm i
            npm run prod-api
          ENDSSH