name: Postman.Express applications runner

on:
  push:
    branches: ["actions"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Deploy to PVM
        env:
          PVM_HOST: ${{ secrets.PVM_HOST }}
          PVM_USERNAME: ${{ secrets.PVM_USERNAME }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh-keyscan -H "$PVM_HOST" >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/Postman.Express $PVM_USERNAME@$PVM_HOST "bash -s" << 'ENDSSH'
            cd ~/Projects/Postman.Express
            git pull origin main
            cd consumer_app
            npm i
            npm run build
            npm run prod-api
            cd ../driver_app
            npm i
            npm run build
            npm run prod-api
            cd ../locker_app
            npm i
            npm run build
            npm run prod-api
            cd ../organization_api
            npm i
            npm run prod-api
          ENDSSH