name: Postman.Express applications runner

on:
  push:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        app: [consumer_app, locker_app, driver_app]
    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install Dependencies and Build Frontend App
        run: |
          npm install
              npm run build
        working-directory: ${{ matrix.app }}


  build-backend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        app: [consumer_app, locker_app, driver_app, organization_api]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies and Run Express API
        run: |
          npm install
          npm run prod-api
        working-directory: ${{ matrix.app }}

  # deploy:
  #   runs-on: self-hosted
  #   needs: [build-frontend, build-backend]  # This ensures deployment happens after builds
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
      
  #     - name: Deploy to PVM
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.PVM_HOST }}
  #         username: ${{ secrets.PVM_USERNAME }}
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         script: |
  #           cd ~/Projects/Postman.Express
  #           git pull origin main
  #           cd ~/Projects/Postman.Express/consumer_app
  #           npm i
  #           npm run build
  #           npm run prod-api
  #           cd ~/Projects/Postman.Express/driver_app
  #           npm i
  #           npm run build
  #           npm run prod-api
  #           cd ~/Projects/Postman.Express/locker_app
  #           npm i
  #           npm run build
  #           npm run prod-api
  #           cd ~/Projects/Postman.Express/organization_api
  #           npm i
  #           npm run prod-api
