name: Postman.Express applications runner

on:
  push:
    branches: ["main"]

jobs:
  build-frontend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        app: [consumer_app, locker_app, driver_app]
    steps:
      - uses: actions/checkout@v3
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
    
      - name: Install Dependencies and Build Frontend App
        run: |
          npm install
              npm run build
        working-directory: ${{ matrix.app }}


  build-backend:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        app: [consumer_app, locker_app, driver_app, organization_api]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Install Dependencies and Run Express API
        run: |
          npm install
          npm run prod-api
        working-directory: ${{ matrix.app }}

