name: Postman.Express applications runner

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, reopened, synchronize]
        branches: ["main"]

jobs:
    check-frontend-build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
                app: [consumer_app, locker_app, driver_app]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies and Build Frontend App
              run: |
                  npm install
                  npm run build
              working-directory: ${{ matrix.app }}

    start-org-api:
        needs: [check-frontend-build]
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
                app: [organization_api]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies and Start Organization API for testing
              run: |
                  npm install
                  npm run run-org-api-for-test &
                  echo "Started run-org-api-for-test with PID $!"
                  ps -f -p $!
              working-directory: ${{ matrix.app }}

    test-apis:
        needs: [check-frontend-build, start-org-api]
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
                app: [consumer_app]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies for Organization API
              run: |
                  npm install
              working-directory: organization_api

            - name: Install Dependencies and Test APIs
              run: |
                  npm install
                  npm run test-consumer-api-cloud
              working-directory: ${{ matrix.app }}

    stop-org-api:
        needs: [check-frontend-build, start-org-api, test-apis]
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
                app: [organization_api]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies and Stop Organization API for testing
              run: |
                  npm install
                  npm run stop-org-api-for-test
              working-directory: ${{ matrix.app }}

    deploy:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        needs: [check-frontend-build, start-org-api, test-apis, stop-org-api]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/id_ed25519
                  ssh-keyscan ${{ secrets.PVM_HOST }} >> ~/.ssh/known_hosts

            - name: Execute deployment commands
              env:
                  HOST: ${{ secrets.PVM_HOST }}
                  USERNAME: ${{ secrets.PVM_USERNAME }}
              run: |
                  ssh $USERNAME@$HOST << 'ENDSSH'
                    cd ~/Projects/PostmanExpress
                    git pull origin main || exit 1
                    cd consumer_app 
                    npm ci || exit 1
                    npm run build || exit 1
                    pm2 restart consumer_app_api || exit 1
                    cd ../driver_app
                    npm ci || exit 1
                    npm run build || exit 1
                    pm2 restart driver_app_api || exit 1
                    cd ../locker_app
                    npm ci || exit 1
                    npm run build || exit 1
                    pm2 restart locker_app_api || exit 1
                    cd ../organization_api
                    npm ci || exit 1
                    pm2 restart organization_api || exit 1
                  ENDSSH
