name: Postman.Express applications runner

on:
    push:
        branches: ["main"]
    pull_request:
        types: [opened, reopened, synchronize]
        branches: ["main"]

jobs:
    check-frontend-build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
                app: [consumer_app, locker_app, driver_app]
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies and Build Frontend App
              run: |
                  npm install
                  npm run build
              working-directory: ${{ matrix.app }}

    deploy:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        needs: [check-frontend-build]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/id_ed25519
                  ssh-keyscan ${{ secrets.PVM_HOST }} >> ~/.ssh/known_hosts

            - name: Execute deployment commands
              env:
                  HOST: ${{ secrets.PVM_HOST }}
                  USERNAME: ${{ secrets.PVM_USERNAME }}
              run: |
                  ssh $USERNAME@$HOST << 'ENDSSH'
                    cd ~/Projects/PostmanExpress
                    git pull origin main
                    cd consumer_app
                    npm i
                    npm run build
                    pm2 restart consumer_app_api
                    cd ../driver_app
                    npm i
                    npm run build
                    pm2 restart driver_app_api
                    cd ../locker_app
                    npm i
                    npm run build
                    pm2 restart locker_app_api
                    cd ../organization_api
                    npm i
                    pm2 restart organization_api
                  ENDSSH
