name: Postman.Express applications runner

on:
    push:
        branches: ["actions-test"]

jobs:
    setup-ssh:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up SSH
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/runner

                  chmod 600 ~/.ssh/runner
                  if [[ $? -ne 0 ]]; then echo "chmod failed" && exit 1; fi

                  eval "$(ssh-agent -s)"
                  if [[ $? -ne 0 ]]; then echo "ssh-agent failed" && exit 1; fi

                  ssh-add ~/.ssh/runner
                  if [[ $? -ne 0 ]]; then echo "ssh-add failed" && exit 1; fi

# just one more test
